# Auto-generated by Amazon Q

resource "aws_ecs_cluster" "testing_cluster" {
  name = "testing-cluster"
  tags = {
    "aws:cloudformation:stack-id" = "arn:aws:cloudformation:us-east-2:842676018479:stack/Infra-ECS-Cluster-testing-cluster-a5c7de03/c40e23b0-6a8d-11f1-9512-028188757dc3"
    "aws:cloudformation:stack-name" = "Infra-ECS-Cluster-testing-cluster-a5c7de03"
    "aws:cloudformation:logical-id" = "ECSCluster"
  }
}

resource "aws_ecs_cluster_capacity_providers" "testing_cluster" {
  cluster_name       = aws_ecs_cluster.testing_cluster.name
  capacity_providers = ["FARGATE", "FARGATE_SPOT"]
}
